little-spoon-dev/design-system

.commitlintrc.js, .github/workflows/build.yml, README.md
[Fix design-system build](https://littlespoon.atlassian.net/browse/LS-1709)
ci: fix commitlint and run build on pull_request
- commitlint fails when release-please PR is merged to master because `scope-empty` errors
- `build` workflow only runs on `push`
- commitlint warns instead of errors for `scope-empty` rule
- `build` workflow also runs on `pull_request`
=> ci: fix commitlint and run build on pull_request LS-1709

.github/workflows/build.yml, release-please-config.json
[Fix release-please in design-system](https://littlespoon.atlassian.net/browse/LS-1713)
ci: fix release-please
- Release PR is stuck waiting for expected `build` status check to pass. See https://github.com/googleapis/release-please/issues/922
- Dependent package versions are not bumped. See https://github.com/googleapis/release-please/issues/1032
- Skip `build` workflow for release PR since GitHub status checks are not run by the bot.
- Going to set [`"always-link-local": true`](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#breaking-versions) to see if that fixes the issue
CI
Release PR breaks
#12
=> ci: fix release-please LS-1713

.github/workflows/build.yml, .github/workflows/publish.yml, lerna.json
[Ignore private packages during design-system publish](https://littlespoon.atlassian.net/browse/LS-1714)
ci(root): don't bump private package version during publish
https://github.com/lerna/lerna/tree/main/commands/version#--no-private
When running lerna [publish](https://github.com/little-spoon-dev/design-system/runs/3613986653?check_suite_focus=true#step:14:18), it bumps versions for private packages:
```
Changes:
- storybook: 1.1.0 => 1.2.0 (private)
- template: 1.0.0-alpha => 1.0.0-alpha.0 (private)
- @littlespoon/theme: 1.0.0 => 1.1.0
```
No longer bump version for private packages when running lerna publish
Manually trigger dry-run publish workflow and verify private packages aren't bumped
=> ci(root): don't bump private package version during publish LS-1714

.github/workflows/publish.yml
[Fix lerna publish in design-system](https://littlespoon.atlassian.net/browse/LS-1716)
ci(root): pass lerna options to publish workflow
Getting errors when running [publish](https://github.com/little-spoon-dev/design-system/runs/3615206717?check_suite_focus=true#step:14:25) workflow:
```
lerna WARN gitPush remote: error: GH006: Protected branch update failed for refs/heads/master.        
lerna WARN gitPush remote: error: Required status check "build" is expected. At least 1 approving review is required by reviewers with write access.        
lerna WARN gitPush To https://github.com/little-spoon-dev/design-system
lerna WARN gitPush  ! [remote rejected] master -> master (protected branch hook declined)
lerna WARN gitPush  ! [remote rejected] @littlespoon/theme@1.1.0 -> …
```
=> ci(root): pass lerna options to publish workflow LS-1716

.github/workflows/publish.yml
[Fix lerna publish in design-system](https://littlespoon.atlassian.net/browse/LS-1716)
ci(root): pass option `--no-verify-access` to lerna publish
[lerna publish errors](https://github.com/little-spoon-dev/design-system/runs/3615413131?check_suite_focus=true#step:14:23):
```
lerna info Verifying npm credentials
lerna http fetch GET 403 https://registry.npmjs.org/-/npm/v1/user 158ms
403 Forbidden - GET https://registry.npmjs.org/-/npm/v1/user
lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
```
See https://github.com/lerna/lerna/issues/2788
Pass option [`--no-verify-access`](https://github.com/lerna/lerna/tree/main/commands/publish#--no-verify-access)
=> ci(root): pass option `--no-verify-access` to lerna publish LS-1716

.github/workflows/release-please.yml, release-please-config.json
[Fix release-please in design-system](https://littlespoon.atlassian.net/browse/LS-1727)
ci(root): fix release-please workflow
release-please-action fails to publish
Replace `release_created` with `releases_created` for manifest releaser. See https://github.com/google-github-actions/release-please-action/issues/317
=> ci(root): fix release-please workflow LS-1727

packages/theme/__tests__/__snapshots__/index.test.ts.snap, packages/theme/src/colors/token.ts
[Add black and white color tokens to @littlespoon/theme](https://littlespoon.atlassian.net/browse/LS-1726)
feat(theme): add shade tokens to theme
Black and white shade token colors not in theme
Black and white shade token colors are in theme
=> feat(theme): add shade tokens to theme LS-1726

packages/button/tsconfig.json, packages/storybook/tsconfig.json, packages/theme/tsconfig.json, scripts/template/tsconfig.json, tsconfig.json
[Refactor tsconfig.json in design-system](https://littlespoon.atlassian.net/browse/LS-1780)
chore(all): default noEmit to true in root tsconfig.json
`noEmit` is false in root `tsconfig.json`
`noEmit` is true in root `tsconfig.json`. `noEmit` is set to false for package `tsconfig.json`.
The change allows `tsconfig.root.json` to be renamed to `tsconfig.json`, which allows IDE to pick up the config
=> chore(all): default noEmit to true in root tsconfig.json LS-1780

release-please-config.json, scripts/create-package.ts, yarn.lock
[Fix `create-package` script in design-system](https://littlespoon.atlassian.net/browse/LS-1793)
fix(scripts): fix JSON stringify in `create-package` script
Running `yarn create-package foo` creates a `package.json` without spaces and indentation
Running `yarn create-package foo` creates a `package.json` with 2 spaces and indentation
=> fix(scripts): fix JSON stringify in `create-package` script LS-1793

packages/button/package.json, templates/react-template/package.json
[Specify react v17 in package peerDependencies in design-system](https://littlespoon.atlassian.net/browse/LS-1801)
Since JSX transform is not supported in versions below 17
`button` and `react-template` has react peerDependencies set to `16 || 17`
`button` and `react-template` has react peerDependencies set to `17`
=> chore(all): specify only react 17 in peerDependencies LS-1801

packages/theme/__tests__/utils.test.ts, packages/theme/src/utils.ts
[Memoize theme util rgb in design-system](https://littlespoon.atlassian.net/browse/LS-1802)
perf(theme): memoize rgb util
Currently theme util `rgb` is not memoized
Theme util `rgb` memoizes value
=> perf(theme): memoize rgb util LS-1802

.github/workflows/publish.yml
Related to #59
[Switch release strategy from release-please to lerna for design-system](https://littlespoon.atlassian.net/browse/LS-1805)
Allow `publish` to be run on CI without triggering workflow dispatch
[publish](https://github.com/little-spoon-dev/design-system/runs/3691477909) is skipped on `master`
Run `publish` on `master`
=> ci(root): run lerna publish without workflow dispatch LS-1805

.eslintrc.json, docs/CONTRIBUTING.md, packages/button/README.md, packages/button/__tests__/Button.test.tsx, packages/button/src/Button.tsx, packages/button/src/ButtonBase.tsx, packages/storybook/src/stories/Button.stories.tsx, packages/storybook/tsconfig.json
[Allow button to be a link in design-system](https://littlespoon.atlassian.net/browse/LS-1777)
To render button links or a different element/component.
Button only renders as `button`.
Button is polymorphic and can render as a different component:
```tsx
<Button as="a" />
<Button as={Route} />
```
=> feat: allow button to render as a different component LS-1777

.github/workflows/build.yml, lerna.json
- ci: run auto-approve on `pull_request_target` in build
- chore: fix `lerna.json` ignoreChanges
- auto-approve runs on `push` in build
- `lerna.json` ignoreChanges has `test` twice
- auto-approve runs on `pull_request_target` in build
- `lerna.json` ignoreChanges has `spec`
=> ci: run auto-approve on pull_request_target in build

packages/button/src/ButtonBase.tsx
https://littlespoon.atlassian.net/browse/LS-1893
Integrating new DS components to Order Modals
DS button inherits width from parent on mobile screens
DS button uses `fit-content` width
`@littlespoon/button`
Browser support: https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content#browser_compatibility
=> feat(button): prevent button from inheriting parent width LS-1893

packages/checkbox/__tests__/Checkbox.test.tsx, packages/checkbox/src/Checkbox.tsx
[Fix "Checkbox" checked state](https://littlespoon.atlassian.net/browse/LS-2126)
Fixes issue introduced in the previous PR
- Uses `aria-checked` attribute.
- Uses `checked` attribute.
=> fix(checkbox): fix checked state LS-2126

packages/button/__tests__/Button.test.tsx, packages/button/src/Button.tsx, packages/button/src/ButtonBase.tsx, packages/storybook/src/stories/Button.stories.tsx
[Add "tertiary" variant to Button in design-system](https://littlespoon.atlassian.net/browse/LS-2152)
- feat(button): add variant `tertiary`
- fix(button): remove focus styles for non-keyboard focus
- Button does not have variant `tertiary` ([ZeroHeight](https://zeroheight.com/3ddd0f892/p/01a397-buttons/t/52ebb4))
- Button has focus styles when mouse is used (we only want focus styles for keyboard use)
- Button has variant `tertiary` ([ZeroHeight](https://zeroheight.com/3ddd0f892/p/01a397-buttons/t/52ebb4))
- Button only has focus styles for keyboard and not mouse
=> feat(button): add variant `tertiary` LS-2152

packages/tag/src/styled.tsx
[Add padding to CloseIcon in Tag Deletable state](https://littlespoon.atlassian.net/browse/LS-2201)
Using this package revealed that the text and icon were adjoined
Text and icon are adjoined
There is space between the text and icon
=> feat(tag): add padding between text and icon LS-2201

yarn.lock
Dependabot upgrades must have missed some things in `yarn.lock`
build(root): update yarn.lock
=> build(root): update yarn.lock

packages/breadcrumbs/src/styled.tsx
[Update breadcrumbs styling to match global link styling](https://littlespoon.atlassian.net/browse/LS-2353)
Breadcrumb links have different styling than newly updated link styles, creating a visual mismatch.
Breadcrumb and link styles are different
Breadcrumb and link styles are the same
=> fix(breadcrumbs): match breadcrumb styling to updated link styling LS-2353

packages/alert/src/AlertBase.tsx
Error:
```
Cannot find module '@littlespoon/theme/src/colors' from 'node_modules/@littlespoon/alert/lib/AlertBase.js'
```
=> fix(alert): fix import of theme colors

packages/icons/README.md, packages/icons/src/index.ts, packages/ui/icons/AccountIcon/index.ts, packages/ui/icons/BillIcon/index.ts, packages/ui/icons/BoxIcon/index.ts, packages/ui/icons/CalendarIcon/index.ts, packages/ui/icons/CaretIcon/index.ts, packages/ui/icons/CartIcon/index.ts, packages/ui/icons/CheckIcon/index.ts, packages/ui/icons/ExclamationIcon/index.ts, packages/ui/icons/GiftCardIcon/index.ts, packages/ui/icons/HamburgerMenuIcon/index.ts, packages/ui/icons/LogoutIcon/index.ts, packages/ui/icons/SubtractIcon/index.ts
[https://littlespoon.atlassian.net/browse/LS-3975](https://littlespoon.atlassian.net/browse/LS-3975)
Imports of new icons, like CalendarIcon are not working on the frontend
Check whether new icons can be properly imported on the frontend
Low risk, only added new imports
=> fix(icons): add exports of new PCH icons LS-3975

packages/icons/__tests__/AddIcon.test.tsx, packages/icons/src/AddIcon.tsx
Update add icon svg as @chantaldegaust provided.
The old icon was created by rotating close icon 45 degrees but the size was different from subtract icon.
=> fix(icons): update add icon

packages/alert/README.md, packages/alert/src/AlertBase.tsx, packages/icons/README.md, packages/icons/src/index.ts, packages/storybook/src/stories/icons/InfoIcon.stories.tsx, packages/ui/__tests__/__snapshots__/index.test.ts.snap, packages/ui/icons/InfoIcon/index.ts
[LS-3944](https://littlespoon.atlassian.net/browse/LS-LS-3944)
Make the Alert full width when relative positioned in the PCH screens
The alert is not filling the space
The relative positioned alert will fill the 100% width:
- Open the StoryBook
- Check if the alert with type as relative occupy the full width
- Ensure that banner and toast types has 800px width to not break in other points.
Alert component
=> chore(alert): adjust width for relative positioned alert - LS-3944

packages/typography/src/TypographyBase.tsx
[[DS] Fix letter spacing for typography package](https://littlespoon.atlassian.net/browse/LS-4066)
The current letter spacing seems to be different than in figma.
- Smoke test to make sure letter spacing is due to the designs
letter spacing for typography package
Low risk
I've tried to make it as close to designs as possible:
=> fix: update letter spacing for typography LS-4066

packages/drawer/__tests__/Backdrop.test.tsx, packages/drawer/__tests__/Drawer.test.tsx, packages/drawer/src/Backdrop.tsx, packages/drawer/src/BackdropBase.tsx, packages/drawer/src/Drawer.tsx, packages/drawer/src/DrawerBase.tsx
[DS: Add animations to the drawer](https://littlespoon.atlassian.net/browse/PCH-352)
Make user flow smoother
The drawer and backdrop just blinks into the view
The drawer slides from the right (or from the bottom for mobile) and the backdrop fades in and out
Review app: https://deploy-preview-766--littlespoon.netlify.app/
Manual QA
Desk check
Drawer
Low risk
https://user-images.githubusercontent.com/58109902/210412694-9f8127cf-9255-440a-89b4-3fdef162c094.mov
[PCH-352]: https://littlespoon.atlassian.net/browse/PCH-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add drawer animations PCH-352

packages/accordion/src/AccordionDetails.tsx
[DS: Fix AccordionDetails for Old iOS Versions](https://littlespoon.atlassian.net/browse/PCH-501)
- Should throw an error when visiting [current accordion storybook](https://littlespoon.netlify.app/?path=/story/design-system-accordion--multiple) with iOS 13.3 or lower
- Should load when visiting [PR's accordion storybook](https://deploy-preview-817--littlespoon.netlify.app/?path=/story/design-system-accordion--multiple) with iOS 13.3 or lower
=> refactor(accordion): fix older iOS ResizeObserver compatibility issue PCH-501

packages/button/__tests__/Button.test.tsx, packages/button/src/Button.tsx, packages/button/src/ButtonBase.tsx, packages/storybook/src/stories/Button.stories.tsx
[[DS] Update button component to support media queries](https://littlespoon.atlassian.net/browse/WEB-1332)
New feature for button
Button doesn't support size by breakpoint
Button supports size by breakpoint
Manual QA
Button size prop
Low risk
=> feat(button): add size by breakpoint support for button WEB-1332
