little-spoon-dev/design-system

.github/PULL_REQUEST_TEMPLATE.md, README.md
[Add pull request template to design-system](https://littlespoon.atlassian.net/browse/LS-1697)
ci(root): add pull request template
No pull request template
Pull request template
=> ci(root): add pull request template LS-1697

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, README.md
[Add Codecov and CodeQL to design-system](https://littlespoon.atlassian.net/browse/LS-1705)
ci(root): add Codecov and CodeQL
No Codecov and CodeQL
Codecov and CodeQL
=> ci(root): add Codecov and CodeQL LS-1705

.github/dependabot.yml, .github/workflows/auto-approve.yml, .mergify.yml
[Auto approve and merge Dependabot PR in design-system](https://littlespoon.atlassian.net/browse/LS-1704)
ci(root): auto approve and merge Dependabot PR
Dependabot PR requires manual approval and merge
Dependabot PR is automatically approved and merged once build checks pass
=> ci(root): auto approve and merge Dependabot PR LS-1704

packages/storybook/package.json, packages/storybook/src/stories/Colors.stories.tsx, packages/storybook/src/stories/Colors.tsx
[Create stories for theme colors in design-system](https://littlespoon.atlassian.net/browse/LS-1711)
feat(storybook): add stories for theme colors
No stories for theme colors
Stories for theme colors
Relates to #11
=> feat(storybook): add stories for theme colors LS-1711

README.md, docs/CONTRIBUTING.md
[Add contributing docs to design-system](https://littlespoon.atlassian.net/browse/LS-1748)
docs(root): split `CONTRIBUTING.md` from `README.md`
Everything in `README.md`, no `CONTRIBUTING.md`
Separate `CONTRIBUTING.md` from `README.md`
=> docs(root): split `CONTRIBUTING.md` from `README.md` LS-1748

package.json, packages/button/.eslintrc.json, packages/button/README.md, packages/button/__tests__/Button.test.tsx, packages/button/__tests__/index.test.ts, packages/button/jest.config.ts, packages/button/package.json, packages/button/src/Button.tsx, packages/button/src/ButtonBase.tsx, packages/button/src/index.ts, packages/button/tsconfig.json, packages/storybook/.storybook/preview-head.html, packages/storybook/package.json, packages/storybook/src/stories/Button.stories.tsx, release-please-config.json, scripts/template/package.json, yarn.lock
[Add primary button to design-system](https://littlespoon.atlassian.net/browse/LS-1722)
feat(button): add primary button LS-1722
No button
Primary button: https://zeroheight.com/3ddd0f892/p/01a397-buttons/t/190120
Depends on #24
=> feat(button): add primary button LS-1722

.github/workflows/publish.yml, README.md, docs/CONTRIBUTING.md
[Document release in design-system](https://littlespoon.atlassian.net/browse/LS-1755)
- ci: tidy `publish.yml`
- docs: document release in `CONTRIBUTING.md`
- Publish workflow has unnecessary input option
- Missing documentation
- Removed publish input option
- Added documentation
=> docs: document release LS-1755

.github/workflows/build.yml, .gitignore, package.json, packages/button/package.json, packages/theme/package.json, scripts/template/package.json
[Speed up `build:flowtypes` in design-system](https://littlespoon.atlassian.net/browse/LS-1758)
build(all): speed up `build:flowtypes` script
Script `build:flowtypes` takes around `26.44s`
Script `build:flowtypes` takes around `10.50s`
=> build(all): speed up `build:flowtypes` script LS-1758

.gitignore, packages/storybook/.gitignore, packages/storybook/package.json, packages/storybook/scripts/copy-changelog.ts, packages/storybook/src/stories/Button.stories.tsx, packages/storybook/src/stories/Colors.stories.tsx, packages/storybook/src/stories/Fonts.stories.tsx, packages/storybook/src/stories/Fonts.tsx
[Render changelog in design-system Storybook](https://littlespoon.atlassian.net/browse/LS-1731)
feat(storybook): render changelog for all packages
No changelog in Storybook
Changelog is rendered in Storybook
=> feat(storybook): render changelog for all packages LS-1731

packages/storybook/package.json, packages/storybook/src/stories/Colors.tsx
[Display color codes in design-system Storybook](https://littlespoon.atlassian.net/browse/LS-1782)
feat(storybook): display color codes
Color rgba/hexadecimal not displayed
Color rgba/hexadecimal displayed
=> feat(storybook): display color codes LS-1782

.eslintrc.json, package.json, packages/button/__tests__/Button.test.tsx, packages/button/src/ButtonBase.tsx, packages/storybook/scripts/copy-changelog.ts, packages/storybook/src/stories/Button.stories.tsx, packages/storybook/src/stories/Button.tsx, packages/storybook/src/stories/Colors.stories.tsx, packages/storybook/src/stories/Colors.tsx, packages/storybook/src/stories/Fonts.stories.tsx, packages/storybook/src/stories/Header.stories.tsx, packages/storybook/src/stories/Header.tsx, packages/storybook/src/stories/Page.stories.tsx, packages/storybook/src/stories/Page.tsx, yarn.lock
[Sort imports in design-system](https://littlespoon.atlassian.net/browse/LS-1786)
style(all): sort import for all packages
Imports are not sorted
Imports are sorted
=> style(all): sort import for all packages LS-1786

.eslintrc.json, package.json, yarn.lock
[Lint code for accessibility in design-system](https://littlespoon.atlassian.net/browse/LS-1753)
chore(root): add "eslint-plugin-jsx-a11y" to .eslintrc.json
No "eslint-plugin-jsx-a11y" to lint JSX for accessibility
Added "eslint-plugin-jsx-a11y" to lint JSX for accessibility
=> chore(root): add "eslint-plugin-jsx-a11y" to .eslintrc.json LS-1753

.eslintrc.json, packages/button/__tests__/Button.test.tsx, packages/button/src/ButtonBase.tsx, packages/storybook/src/stories/Button.stories.tsx, packages/storybook/src/stories/Header.stories.tsx, packages/storybook/src/stories/Header.tsx, packages/storybook/src/stories/Page.stories.tsx, packages/storybook/src/stories/Page.tsx
[Refactor design-system components](https://littlespoon.atlassian.net/browse/LS-1789)
refactor: tidy button and stories
Code can be refactored to improve organization and DRY
- Refactored Button code and tests
- Created separate templates for Button stories
=> refactor: tidy button and stories LS-1789

templates/react-template/jest.config.ts
[Tidy design-system react-template](https://littlespoon.atlassian.net/browse/LS-1794)
chore(react-template): tidy jest.config.ts
Redundancy in react-template `jest.config.ts` with `jest.root.ts`
Simplified react-template Jest config
=> chore(react-template): tidy jest.config.ts LS-1794

.github/workflows/build.yml, .mergify.yml
[Don't skip build for GitHub bot on design-system](https://littlespoon.atlassian.net/browse/LS-1807)
ci(root): don't skip build when actor is github bot
`build` workflow is skipped for GitHub bot (e.g., lerna release)
`build` workflow is not skipped for GitHub bot
=> ci(root): don't skip build when actor is github bot LS-1807

packages/button/CHANGELOG.md, packages/storybook/CHANGELOG.md, packages/storybook/scripts/copy-changelog.ts, packages/theme/CHANGELOG.md, packages/ui/CHANGELOG.md
[Fix changelog in design-system](https://littlespoon.atlassian.net/browse/LS-1808)
Given we have moved from Release Please to Lerna for changelog generation, we need to fix the changelog for the latest release and fix Storybook changelog stories
- Redundant changelogs
- Storybook changelog stories incorrect
- Fixed changelogs
- Fixed Storybook changelog stories
=> docs(packages): fix `CHANGELOG.md` and Storybook LS-1808

docs/CONTRIBUTING.md
[Document gotchas with Lerna release in design-system](https://littlespoon.atlassian.net/browse/LS-)
docs(root): update CONTRIBUTING with Lerna release gotchas
Lerna release gotchas not documented
Lerna release gotchas documented
=> docs(root): update CONTRIBUTING with Lerna release gotchas LS-1809

README.md, docs/CONTRIBUTING.md, packages/icons/.eslintrc.json, packages/icons/README.md, packages/icons/__tests__/ArrowIcon.test.tsx, packages/icons/__tests__/__snapshots__/index.test.ts.snap, packages/icons/__tests__/index.test.ts, packages/icons/jest.config.ts, packages/icons/package.json, packages/icons/src/ArrowBase.tsx, packages/icons/src/ArrowIcon.tsx, packages/icons/src/index.ts, packages/icons/tsconfig.json, packages/storybook/package.json, packages/storybook/src/stories/ArrowIcon.stories.tsx, packages/ui/__tests__/index.test.ts, packages/ui/icons/ArrowIcon/index.ts, packages/ui/icons/index.ts
[Add arrow icon](https://littlespoon.atlassian.net/browse/LS-1817)
Pass tests and confirm that there is a x-small, small, medium, and large arrow in Storybook
=> feat(icons): add arrow icon LS-1817

lerna.json, packages/ui/package.json
[Add icons to ui dependencies](https://littlespoon.atlassian.net/browse/LS-1837)
=> fix(ui): add icons to ui dependencies LS-1837

.commitlintrc.js, README.md
chore(root): remove divider-curve from commitlint, update root readme
=> chore(root): remove divider-curve from commitlint, update root readme

.github/workflows/publish.yml
[Fix design-system publish](https://littlespoon.atlassian.net/browse/LS-1894)
ci(root): fix publish workflow
Lint runs before build in publish
Lint runs after build in publish (and commitlint is removed)
=> ci(root): fix publish workflow LS-1894

packages/theme/__tests__/__snapshots__/index.test.ts.snap, packages/theme/src/colors/token.ts, packages/ui/__tests__/__snapshots__/index.test.ts.snap
[Add sub-surface-dull to the DS colors](https://littlespoon.atlassian.net/browse/LS-1890)
feat(theme): add sub surface dull color
=> feat(theme): add sub surface dull color LS-1890

packages/checkbox/__tests__/Checkbox.test.tsx, packages/checkbox/src/Checkbox.tsx, packages/checkbox/src/icons.tsx, packages/checkbox/src/styled.tsx, packages/storybook/src/stories/Checkbox.stories.tsx
[Fix "Checkbox" component on DS](https://littlespoon.atlassian.net/browse/LS-2076)
- [Checkbox stories](https://deploy-preview-152--littlespoon.netlify.app/?path=/story/design-system-checkbox--default
)
This is a bug fix to support external state changes.
The state is part of the `Checkbox`, which makes it impossible to update externally. 
For example, a filter that uses checkboxes and a reset functionality won't be able to reflect the reset state on the checkboxes because they won't update based on external data.
There is no state. The component relies on `props` to show the UI changes.
- Manual test on storybook, the stories should keep the original behavior.
- Checkbox
- It should be safe to introduce these changes since we are only using this in one place on the FE where we are …
=> fix(checkbox): fix Checkbox LS-2076

packages/checkbox/src/Checkbox.tsx, packages/checkbox/src/icons.tsx, packages/checkbox/src/styled.tsx
[Fix Checkbox in design-system](https://littlespoon.atlassian.net/browse/LS-2304)
fix(checkbox): fix Checkbox focus state and improve icons
- Checkbox focus state is invalid
- Checkbox focus state is correct
- Icons optimized
Compare Netlify preview with https://littlespoon.netlify.app/?path=/story/design-system-checkbox--default
=> fix(checkbox): fix Checkbox focus state and improve icons LS-2304

README.md, packages/link/.eslintrc.json, packages/link/README.md, packages/link/__tests__/Link.test.tsx, packages/link/__tests__/index.test.ts, packages/link/jest.config.ts, packages/link/package.json, packages/link/src/Link.tsx, packages/link/src/LinkBase.tsx, packages/link/src/index.ts, packages/link/tsconfig.json, packages/storybook/src/stories/Link.stories.tsx, packages/ui/Link/index.ts, packages/ui/__tests__/__snapshots__/index.test.ts.snap, packages/ui/index.ts, packages/ui/package.json
[Add Link to Design System](https://littlespoon.atlassian.net/browse/LS-2202)
feat: add Link
No Link
Link: https://zeroheight.com/3ddd0f892/p/1026a1-link/b/8982a2
Storybook
=> feat: add Link LS-2202

packages/breadcrumbs/__tests__/Breadcrumbs.test.tsx, packages/divider/__tests__/Divider.test.tsx, packages/typography/__tests__/Typography.test.tsx
[Remove unnecessary @ts-ignore comment in design-system](https://littlespoon.atlassian.net/browse/LS-2325)
chore(all): remove unnecessary `@ts-ignore` comment
=> chore(all): remove unnecessary @ts-ignore comment LS-2325

docs/CONTRIBUTING.md, package.json, packages/box/package.json, packages/breadcrumbs/package.json, packages/button/package.json, packages/checkbox/package.json, packages/divider/package.json, packages/icons/package.json, packages/link/package.json, packages/storybook/package.json, packages/tag/package.json, packages/theme/package.json, packages/typography/package.json, packages/ui/package.json, templates/react-template/package.json, templates/typescript-template/package.json
[Add script `lint:tsc` to design-system](https://littlespoon.atlassian.net/browse/LS-2326)
chore(all): add script `lint:tsc` to packages and templates
=> chore(all): add script `lint:tsc` to packages and templates LS-2326

packages/button/src/ButtonBase.tsx, packages/link/src/LinkBase.tsx, packages/storybook/src/stories/icons/ArrowIcon.stories.tsx, packages/storybook/src/stories/icons/FilterIcon.stories.tsx, packages/theme/README.md, packages/theme/__tests__/__snapshots__/index.test.ts.snap, packages/theme/__tests__/index.test.ts, packages/theme/src/colors/primary.ts, packages/theme/src/colors/token.ts, packages/ui/__tests__/__snapshots__/index.test.ts.snap
[Add brand to theme colors primary](https://littlespoon.atlassian.net/browse/LS-2313)
feat(theme): add brand to theme colors primary
https://zeroheight.com/3ddd0f892/p/028ae9-colors/b/8982a2/t/12d188
- Theme color primary blue
- Theme color primary brand (blue is not removed, only deprecated)
https://deploy-preview-174--littlespoon.netlify.app/?path=/story/design-system-theme-colors--primary
=> feat(theme): add brand to theme colors primary LS-2313

.github/workflows/codeql-analysis.yml, .github/workflows/publish.yml, README.md, docs/CONTRIBUTING.md
Rename default branch from `master` to `main`
=> ci(root): rename default branch from master to main LS-3071

packages/breadcrumbs/src/styled.tsx, packages/label/CHANGELOG.md, packages/label/README.md, packages/label/src/Label.tsx, packages/label/src/LabelBase.tsx, packages/storybook/src/stories/Label.stories.tsx, packages/storybook/src/stories/icons/ArrowIcon.stories.tsx, packages/storybook/src/stories/icons/FilterIcon.stories.tsx, packages/theme/README.md
Relates to #568
[Fix Storybook examples for label](https://littlespoon.atlassian.net/browse/LS-3794)
- fix: improve Storybook stories for label
- refactor: update color usage
Storybook stories for label does not match [ZeroHeight](https://zeroheight.com/3ddd0f892/p/336556-label/b/782849)
Storybook stories for label matches [ZeroHeight](https://zeroheight.com/3ddd0f892/p/336556-label/b/782849)
Verify Netlify deploy preview: https://deploy-preview-574--littlespoon.netlify.app/?path=/story/design-system-label--default
Storybook, label, colors
=> fix: improve Storybook stories for label LS-3794

packages/icons/README.md, packages/icons/__tests__/CheckIcon.test.tsx, packages/icons/__tests__/ExclamationIcon.test.tsx, packages/icons/src/CheckBase.tsx, packages/icons/src/CheckIcon.tsx, packages/icons/src/ExclamationBase.tsx, packages/icons/src/ExclamationIcon.tsx, packages/icons/src/index.ts, packages/storybook/src/stories/icons/CheckIcon.stories.tsx, packages/storybook/src/stories/icons/ExclamationIcon.stories.tsx
https://littlespoon.atlassian.net/browse/LS-3819
Add checkmark and exclamation icons in icons package
=> feat(icons): add checkmark and exclamation mark icons LS-3819

packages/icons/README.md, packages/icons/__tests__/SubtractIcon.test.tsx, packages/icons/src/SubtractIcon.tsx, packages/icons/src/SubtractIconBase.tsx, packages/icons/src/index.ts, packages/storybook/src/stories/icons/SubtractIcon.stories.tsx
https://littlespoon.atlassian.net/browse/LS-3892
Create subtract icon in icons package
=> feat(icons): create subtract icon LS-3892

packages/drawer/__tests__/Backdrop.test.tsx, packages/drawer/__tests__/Drawer.test.tsx, packages/drawer/src/Backdrop.tsx, packages/drawer/src/Drawer.tsx, packages/drawer/src/DrawerBase.tsx, packages/storybook/src/stories/Drawer.stories.tsx
[[DS] Improve Drawer Component](https://littlespoon.atlassian.net/browse/LS-3977)
After having a chat with Chantal, I realized that it was necessary to improve the Drawer component by adding/replacing some props so that developers can have more control over its behavior.
Added/Replaced props are:
- `ariaLabel`: ARIA label of the component
- `disableBackdropClick`: If `true`, clicking the Backdrop will not fire the `onClose` callback
- `disableEscapeKeyDown`: If `true`, pressing the Escape key will not fire the `onClose` callback
Feature
Desk check with Chantal / Lu
- https://littlespoon.atlassian.net/browse/LS-3567
- https://littlespoon.atlassian.net/browse/LS-3952
=> feat(drawer): improve drawer LS-3977

packages/drawer/README.md, packages/drawer/__tests__/Backdrop.test.tsx, packages/drawer/__tests__/Drawer.test.tsx, packages/drawer/src/Drawer.tsx, packages/drawer/src/DrawerBase.tsx, packages/storybook/src/stories/Drawer.stories.tsx
[[DS] Improve Drawer component (part 2)](https://littlespoon.atlassian.net/browse/LS-4025)
In order to achieve pixel perfection in the `ConfirmationDrawer` component used in https://github.com/little-spoon-dev/little-spoon-frontend/pull/2537 the following changes are required in the `Drawer` component:
- `Drawer` component must be styleable (via a `className` prop)
- `Drawer` component must not set `min-height` and `min-width` CSS properties
- Desk check with Chantal/Louis
- https://github.com/little-spoon-dev/little-spoon-frontend/pull/2537
=> feat(drawer): improve Drawer component (part 2) LS-4025

packages/alert/src/AlertBase.tsx, packages/icons/README.md, packages/icons/src/index.ts, packages/storybook/src/stories/icons/InfoIcon.stories.tsx, packages/ui/__tests__/__snapshots__/index.test.ts.snap, packages/ui/icons/InfoIcon/index.ts
[LS-4028](https://littlespoon.atlassian.net/browse/LS-4028)
- Fix testing issue in Alert component
- Update InfoIcon component
Manual Test
InfoIcon, Alert components
=> fix: info icon issue

packages/storybook/src/stories/Typography.stories.tsx, packages/typography/__tests__/Typography.test.tsx, packages/typography/src/Typography.tsx, packages/typography/src/TypographyBase.tsx
[Support variant by breakpoint](https://littlespoon.atlassian.net/browse/LS-4105)
- Test
- Storybook smoke test
- Website smoke test after merging
Typography package variant prop
Low risk, smoke test across web should be enough.
=> feat/support variant by breakpoint LS-4105

packages/alert/__tests__/Alert.test.tsx, packages/alert/src/Alert.tsx, packages/alert/src/AlertBase.tsx, packages/alert/src/AlertProvider.tsx, packages/alert/src/index.ts, packages/icons/src/InfoIcon.tsx, packages/storybook/package.json, packages/storybook/src/stories/Alert.stories.tsx
[LS-4062](https://littlespoon.atlassian.net/browse/LS-4062)
Make Alert component with type="toast" to behave as a Toaster component
Manual test
Alert component
=> [LS-4062] feat(alert): update toast component

packages/alert/__tests__/Alert.test.tsx, packages/alert/package.json, packages/alert/src/Alert.tsx, packages/alert/src/AlertBase.tsx, packages/alert/src/AlertProvider.tsx, packages/storybook/src/stories/Alert.stories.tsx
[UI Fixes for Alert Component](https://littlespoon.atlassian.net/browse/LS-4064)
- Review storybook: https://deploy-preview-686--littlespoon.netlify.app/?path=/story/design-system-alert--toast-stack
- Tests
- Desk check
=> fix(alert): fix alert ui issues

packages/alert/__tests__/Alert.test.tsx, packages/alert/src/Alert.tsx, packages/alert/src/AlertBase.tsx, packages/alert/src/AlertProvider.tsx, packages/storybook/src/stories/Alert.stories.tsx, packages/storybook/src/stories/Drawer.stories.tsx
[[DS] Improve Alert component](https://littlespoon.atlassian.net/browse/SP-972)
Make `Alert` component more flexible
- `Alert` component consumers can now set the `children` and `closeButtonTitle` props
- `Alert` component no longer exposes the  `description`, `actionLinkText` and `actionLinkUrl` props
Add unit tests
`Alert` component
=> feat(alert): improve Alert component SP-972

scripts/create-package.ts
[[DS] Clean up create-package script](https://littlespoon.atlassian.net/browse/PCH-1252)
`dependabot` created #1018. However, it was impossible to bump `lerna` dependency due to [an error](https://github.com/little-spoon-dev/design-system/actions/runs/6011220168/job/16304161348). 
Consequently, after reading https://lerna.js.org/docs/legacy-package-management, @huhgawz applied some changes to #1018 in order to fix the errors that were making impossible to bump `lerna` dependency to the `7.x` version:
1. `useWorkspaces` option was removed from the `lerna.json` file (fixed in 661f3e69e2001b7c0d131a2faa7b122d98392118)
2. `add` command was removed from Lerna CLI (fixed in c87837222d2252c23d0bd803e8cd87b1c2e4ccb2, 560b31776b71fc8aeb070d493ae45b31a64d3214, …
=> feat: clean up create-package script
